### ISSUE TITLE
Question: provide initial estimate of the pose to the solver

### ISSUE THREAD

**Issue by facontidavide** [terzakig/sqpnp#19]
Hi,

is it possible to add an initial estimate of the pose to make the solver converge faster.

A typical use case during tracking would be to use the previous solution as an initial seed to the solver.

thanks again for the fantastic work!

**Comment by terzakig** [comment]
Hi Davide, thank you again for your interest and comments!

So, this algorithm works on the classic quadratically constrained quadratic program (QCQP) for the PnP and the initial solutions (i.e., the projections of the minimizing eigenvector of the quadratic matrix) come with certain guarantees that the solution will be reached in at least one of the sequential quadratic programming descents from these initial points. So, if you have an estimate that is closer to the minimum, that could probably precipitate convergence, but it could also lead to divergence in rare -but not impossible- cases because these conditions/guarantess no longer apply necessarily. So, the answer is yes, but with two caveats: a) How would you get this estimate and, b) Can it always converge to the intended point (i.e., the converged solution you would normally get)? And let's think about the gain: SQP usually converges in 5-10 iterations. So, all in all,  the gain would be 5, maybe 10 (in a far-fetched case) steps in the SQP process, which is significant, but not a lot, if you consider that the SQP system is solved without a matrix inversion (actually, an analytical version of the 3x3) taking place.

So, certainly, a "special" estimate  that precipitates convergence can be found somehow (perhaps via prior knowledge, other sensor, etc.?), but the how, and the computational trade-off should be considered in your case.
